#!/usr/bin/env bash
# 7-highlander: This script displays "To infinity and beyond" indefinitely.
echo "7-highlander process started. PID: $$"
echo "I will print 'To infinity and beyond' and declare invincibility if you send me SIGTERM."
trap 'echo "I am invincible!!!"; exit 0' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2 
done

