#!/usr/bin/env bash
# 7-highlander: This script displays "To infinity and beyond" indefinitely.
trap 'echo "I am invincible!!!"; exit 0' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2 
done

